apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-search2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hybrid-search2
  template:
    metadata:
      labels:
        app: hybrid-search2
    spec:
      containers:
        - name: hybrid-search2
          image: us-central1-docker.pkg.dev/my-project/hybrid-search/hybrid-search2:latest
          ports:
            - containerPort: 8080
